name: Test

on: pull_request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn Build
      - name: Lint
        run: yarn lint
